# Generated by Django 4.0.6 on 2022-07-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.FloatField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
