# Generated by Django 4.0.6 on 2022-07-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parientes',
            name='tipo_de_parentezco',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parientes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
